### ISSUE TITLE
Make the game easier to build

### ISSUE THREAD

**Issue by SuperV1234** [SuperV1234/SSVOpenHexagon#101]
The current build scripts require superuser permissions. 
I need to find a way to avoid installing the SSV dependency libraries on the user's system, and instead compile them in a temporary folder and use that folder as an include path in the build system.

**Comment by matijaskala** [comment]
This script can be used to make a unified tarball.
(deleted the code)

**Comment by Morxemplum** [comment]
I mean on July 16th this has been done, otherwise I wouldn't be here now. Closing this
