### ISSUE TITLE
Missing library on Ubuntu 14.04

### ISSUE THREAD

**Issue by jonnius** [SuperV1234/SSVOpenHexagon#108]
Trying to start 2.0-RC1 on Ubuntu 14.04, but get the message:

./x86/SSVOpenHexagon: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory

In the repository I only find libpng12. Any chance to play the game on Ubuntu?

**Comment by darealshinji** [comment]
Remove all files **but** the following from the directory `x86`:
```
libGLEW.so.1.10
libGLEW.so.1.10.0
liblua5.1.so.5.1
liblua5.1.so.5.1.5
libsfml-audio.so.2
libsfml-audio.so.2.1
libsfml-graphics.so.2
libsfml-graphics.so.2.1
libsfml-network.so.2
libsfml-network.so.2.1
libsfml-system.so.2
libsfml-system.so.2.1
libsfml-window.so.2
libsfml-window.so.2.1
SSVOpenHexagon
```
Then change the permissions of the executable: `chmod 0755 x86/SSVOpenHexagon`

The game should now run. On non-Ubuntu/Mint distros it should work too if you also leave `libjpeg.so.8` and `libjpeg.so.8.0.2`.

**Comment by jonnius** [comment]
Thanks for the answer. I am not using Ubuntu 14.04 any more, nut Ubuntu GNOME 15.10. I just downloaded the recent version from humble bundle and it works like a charm without any bug...

**Comment by darealshinji** [comment]
Ok. Anyway, here's a portable build that includes all dependencies which might be missing or cause trouble on different systems: https://drive.google.com/file/d/0BxClEVSW8QykaGkyOHRVazFoOUk/view?usp=sharing

**Comment by jonnius** [comment]
I confused Super Hexagon with Open Hexagon...
Now I installed 2.0-RC2 (deb) and got that message (during install):

**Comment by darealshinji** [comment]
That package is not well build. It's actually not much different from downloading and extracting a tarball.
Try the build that I have posted in my previous comment. Or download the Linux archive from the official homepage (`OpenHexagon2.0-RC1.xz`), rename it's extension to `.tar` and try the suggestions from my first comment.
I'm a bit in a middle of creating a .deb with a menu entry, resolving dependencies and everything. I'll post a link when I'm finished and tested it.

**Comment by darealshinji** [comment]
Here's my `.deb`: https://drive.google.com/file/d/0BxClEVSW8QykSHU3Sy0zLU1qV3M/view?usp=sharing

**Comment by jonnius** [comment]
With your deb it works fine! Thanks
