### ISSUE TITLE
[enhancement] Pulse synchronisation?

### ISSUE THREAD

**Issue by ornithologistnightmare** [SuperV1234/SSVOpenHexagon#109]
I'm having trouble getting the pulses of the walls, the wall colours and the central polygon just right for my own level. I would consider adding an option to synchronise any two of the three and/or all three to each other or any one/two or all three to the music loudness itself (like in Hexagon and Super Hexagon) to make things easier.

I'm using version 1.92 (as I'm not really sure about the "switch" feature of 2.0RC-2).

In the meantime, here's the relevant part of the level file that I want to tweak:

"pulse_min": 100,
    "pulse_max": 110,
    "pulse_speed": 3,
    "pulse_speed_r": 2,
    "pulse_delay_max": 16.4,

```
"beatpulse_max": 17,
"beatpulse_delay_max": 24.8,
```

I'm trying to get the pulse of the walls (top section) to match the pulse of the central polygon (lower section) but even systematic calculations have failed to help me.

Here's the relevant part of the "styles" file:

// Pulse options
    "pulse_min": 0,
    "pulse_max": 1.5,
    "pulse_increment": 0.060625,

I'm also trying to get this to match the pulse of the central polygon.

Anyway, thanks for building this great game. It allows me to customise my levels and make them harder.

**Comment by Morxemplum** [comment]
This is an issue pertaining to the 1.92 version of Open Hexagon, a version of Open Hexagon we no longer maintain and support. If this is an issue that still persists in the latest version of Open Hexagon feel free to re-open the issue. In the meantime, I'm closing this issue.
