### ISSUE TITLE
[Enhancement][Idea] Tournament edition/mode

### ISSUE THREAD

**Issue by Phitherek** [SuperV1234/SSVOpenHexagon#110]
I just thought that it would be really cool to make a Tournament Edition or make a Tournament mode in Open Hexagon. The idea is as follows:
- There is a host who runs a small server to which each Open Hexagon Tournament player (client) can connect. All clients enter waiting mode after connection and setting up nickname.
- When all players are connected to the server, the host can choose a level and tournament duration time (or maybe an option to end manually).
- When this is set up, all clients possibly simultaneously start the selected level with clean hi-scores.
- When the time runs out, the clients are given time to finish the session but cannot restart the game any more. The highest score (time) from each client is transferred to the server.
- The host sees nice summary and announces the winner.

What do you think? I would try to make this myself if I had time for this...

**Comment by Morxemplum** [comment]
This is not feasible to implement. In addition, you don't have to use game code to host Open Hexagon tournaments. You can refer to the "Open Icosagon" tournament that was held back in 2016 as a good example of how to host an Open Hexagon tournament. Closing.
