### ISSUE TITLE
[bug?] Broken patterns...

### ISSUE THREAD

**Issue by ornithologistnightmare** [SuperV1234/SSVOpenHexagon#111]
I have been making a bunch of patterns for my level pack (search "HyperPack" on GitHub to find it) and have been noticing broken patterns popping up all over the place.

This happens, for example, with the Hyper Tunnel (a highly configurable custom pattern that I made as a generic framework for any tunnel pattern that I want to create).

Here is a particular iteration of the Hyper Tunnel.

![image](https://cloud.githubusercontent.com/assets/7671948/5558074/920a0788-8d10-11e4-8292-9afb07b56e83.png)

The wall at the end branches off smoothly into the arm. This is not the case in the second frame that I have captured.

![image](https://cloud.githubusercontent.com/assets/7671948/5558097/3c0d6e5a-8d11-11e4-9d78-909da38c3f0b.png)

The large walls are now protruding out from the arm, giving them a grotesque, broken look. That particular pattern was also much shorter (in terms of its duration - the number of arms) than it should have been, indicating that it was cut.

The code for the pattern (in the level and in the patterns file) is as follows:

---

pFlexDelayHyperTunnelCT(math.random(4, 6), 0.75, 1, 0, 2, 1)

---

function pFlexDelayHyperTunnelCT(mTimes, cThicknessMult, mDelayMult, mExtraFree, mLargeWalls, mArmThicknessDecay, mSpokes)

```
if debuglog == 1 then
    print("[DebugLog]", "Pattern name: Hyper Tunnel [FlexDelay, CT] -GLOBAL-")
end

if mExtraFree == nil then
    mExtraFree = 0
end

if mLargeWalls == nil then
    mLargeWalls = 1
end

if mArmThicknessDecay == nil then
    mArmThicknessDecay = 0
end

if mSpokes == nil then
    mSpokes = 1
end

mDelayMult = mDelayMult * (getSides() / 6)

oldThickness = THICKNESS
startSide = getRandomSide()
direction = (math.random(0, 1) * 2) - 1
myThickness = getHypPerfectThickness(THICKNESS) * cThicknessMult / 2.51 * 2 * (6 / getSides())
delay = getHypPerfectDelay(myThickness) * 12.55 * mDelayMult * (6 / getSides()) / (getDifficultyMult() * cThicknessMult)

for i = 0, mTimes do
    for s = 1, mSpokes do
        if i < mTimes then
            for j = 0, mLargeWalls - 1 do
                wall(startSide + j + ((s * getSides()) / mSpokes), ((((((getSides() - (j * mSpokes) - 1 - mExtraFree - mLargeWalls) / mSpokes)^(mArmThicknessDecay)) * myThickness)) / 2.5) + (delay * getLevelValueFloat("speed_multiplier") * 5.02))
            end
        end
        for j = 0, mLargeWalls - 1 do
            wall(startSide + j + ((s * getSides()) / mSpokes), ((((getSides() - 1 - mExtraFree - mLargeWalls))^(mArmThicknessDecay)) * myThickness))
        end
        for j = 0, (getSides() / mSpokes) - mLargeWalls - mExtraFree - 2 do
            wall(startSide + ((j + 1) * direction) + ((((direction * 0.5) + (0.5)) * (mLargeWalls - 1)) + ((s * getSides()) / mSpokes)), ((((getSides() - (j * mSpokes) - 1 - mExtraFree - mLargeWalls))^(mArmThicknessDecay)) * myThickness))
        end
    end

    wait(delay)

    direction = direction * -1
end

wait(getHypPerfectDelay(THICKNESS) * 3)

THICKNESS = oldThickness
```

end

---

Clearly the pattern (shown above) has been prematurely ended (otherwise the stack under "if i < mTimes" would not have been carried out). This hasn't just been happening with the Hyper Tunnel, but also with other patterns. I mention the Hyper Tunnel only because of its complexity (this causes the glitch to happen frequently).

It cannot be a timeout error (this does not happen with patterns that exceed a particular duration - and some patterns do work, so there is no "deadline" for the ends of patterns), nor an error in my code, so I am all out of ideas. Is there a way to fix this?

**Comment by Morxemplum** [comment]
This bug is not relevant to the Open Hexagon source code or any of the programmer levels. Please keep issues to issues that have to do with the Open Hexagon source code or the default level packs. Closing this.
