### ISSUE TITLE
[enhancement] "mFrameTime" (without using "onUpdate()")

### ISSUE THREAD

**Issue by ornithologistnightmare** [SuperV1234/SSVOpenHexagon#112]
Is there a way to make "mFrameTime"  accessible without having to use the "onUpdate()" function (for example - in files that contain patterns and sequencing helpers)? It would be useful for static delays and thicknesses.

I'm trying to create static delays for my spirals. There was originally a slight gap between each wall and I wanted to use mFrameTime to get it working perfectly. I have a workaround in place (multiplied the delay by 0.75) but I still think that the variable has the potential to be used for static delays.

**Comment by MultHub** [comment]
Random update: l_getLevelTime()

**Comment by Morxemplum** [comment]
You can simply work around this by casting the value mFrameTime to a different variable that can be used outside of the onUpdate function. Closing this.
