### ISSUE TITLE
user files not stored in HOME (linux)

### ISSUE THREAD

**Issue by diggit** [SuperV1234/SSVOpenHexagon#115]
All files written at runtime should be located in user's HOME folder. (User has rights to write only there.)
Here is a messy sketch how to get such path. In case of missing folder, create it...
https://gist.github.com/diggit/8b00a85bc602778697ba
IDK where to put such function, due to various files accesses in entire project. (config.json, users.json, log.txt) So no patch submited.

**Comment by dieeasy** [comment]
+1
had to change file permissions in /usr/local/games/SSVOpenHexagon/ to be able to keep configuration/records (playing 2.0RC2 from .deb package)
