### ISSUE TITLE
[building bug?] CMakeLists everywhere?

### ISSUE THREAD

**Issue by ornithologistnightmare** [SuperV1234/SSVOpenHexagon#116]
I'm getting errors where the build scripts cannot find CMakeLists - even though it's in the source directory. It's looking for the file in random places (like the system root and the Documents library). This is preventing me from building the program. I known that build-win-new.sh is experimental, but surely build-win.bat should work.

This error is causing there to be no files to be passed to MinGW as a result of the "absence" of CMakeLists - though it should all be there.

**Comment by diggit** [comment]
From which directory do you execute that script? Exact error message could tell us more.

**Comment by DeathHammer000** [comment]
Here's the log (generated during a run of build-win-new.sh): http://pastebin.com/04Quhk4T

I'm executing it from the "SSVOpenHexagon" directory (where all of the batch files are). The errors my have changed (I have since reinstalled multiple MinGW packages and also updated MSYS Git from "1.8.4-preview" to "1.9.5-preview" to fix issues with "make").

**Comment by diggit** [comment]
It looks like a problem with external libs. You can try to remove all files from `C:/OHWorkspace` before building. This script do not handle existing files/directories.

**Comment by DeathHammer000** [comment]
More errors (after trying that). http://pastebin.com/ti8TE2bv

I tried to set some of the variables using the CMake GUI and it's still failing.

**Comment by diggit** [comment]
Is that a complete log? SFML library is downloaded by script automaticaly, same as lua. Interesting, that SSVCMake is not missing now. I'll try to run this script on my linux machine with few modifications to verify functionality. These scripts definitely needs some care.

**Comment by diggit** [comment]
Script looks ok to me, after executing `sh ./build-win-new.sh` lua and SFML got downloaded and SFML built. Even main build part started. Many CMAKE variables are hard defined in build script. So some environment variables changes would give no effect.

**Comment by DeathHammer000** [comment]
Seeing as I run Windows, what can I do? I'm just completely stuck.

**Comment by SuperV1234** [comment]
Sorry for the hassle, I rarely use Windows for programming and the scripts are of poor quality and updated. However, by downloading SFML, LUA and the other required libraries, you should be able to use CMake-GUI to manually set variables such as ` LUA_INCLUDE_DIR` to the right location.
If that still doesn't work, could you post a screenshot of your CMake-GUI with set variables?

**Comment by DeathHammer000** [comment]
Whoops. I use the file under /lib, not /build. Will see if this works.

**Comment by Zly-u** [comment]
The issue is fixed since we got a much better build method.
