### ISSUE TITLE
focus (LShift) cannot be undone

### ISSUE THREAD

**Issue by dieeasy** [SuperV1234/SSVOpenHexagon#118]
I play OpenHexagon 2.0-RC2 on Debian sid, installed from the .deb package provided [on the homepage](http://vittorioromeo.info/Misc/Temp/OpenHexagon2.0-RC2.deb).

I can play fine locally (not online but that's another issue), except sometimes after playing back and forth the available levels the triangle just moves way too slowly.

I did some tests and this seems to simply be the "focus" (left shift) command staying "on" and never getting the triangle back to normal speed. This way all levels become unplayable. To fix it I need to entirely quit the game and launch it again.

**Comment by SuperV1234** [comment]
I cannot reproduce the issue. Is there are other detail you could give me?
Also, servers are currently offline.

**Comment by SuperV1234** [comment]
Feel free to reopen if you can reproduce the issue. Please add the steps in that case.
