### ISSUE TITLE
"./build-repository-rel.sh -s" will produce "rm -Rf /*" 

### ISSUE THREAD

**Issue by vedard** [SuperV1234/SSVOpenHexagon#119]
This will delete everything in home folder and more if the script is root

**Comment by SuperV1234** [comment]
What is the best way of making the script safer? I already ask for confirmation before deleting the files. Not sure what should be done to prevent mistakes

**Comment by vedard** [comment]
I don't know what is the right way to make this script safe, but one thing you could is to verify that the "absolutePath" can't  be empty. Now it only check if the first parameter is empty, wich is normally the path but you can't be sure (user like me are sometime idiot and don't read all instruction)

**Comment by vedard** [comment]
Steam had pratically the same problem recently
http://askubuntu.com/questions/574686/steam-install-can-erase-my-home-how-to-prevent-it
