### ISSUE TITLE
Syntax error in cmake code at SSVOpenHexagon/extlibs/SSVCMake/cmake/modules/Common.cmake:87 + Solution

### ISSUE THREAD

**Issue by MisterDood** [SuperV1234/SSVOpenHexagon#121]
When trying to build the latest version of Open Hexagon on Gentoo with g++ 4.8.4 and cmake 2.8.12.2, I kept getting the following build error:

    $ ./build-repository-rel.sh ../bin
    Installation path: /home/misterdood/Games/openhexagon/bin
    Non-release mode activated - RPATH will not be skipped
    Normal user mode activated - SSV libraries will be compiled in a temp folder
    Continue? [Y/N] Y
    projectName: SSVOpenHexagon
    buildType: Release
    makeJobs: 4
    destinationDir: /home/misterdood/Games/openhexagon/bin/
    cmakePrefixPath: /home/misterdood/Games/openhexagon/bin/temp
    cmakeFlags: -DCMAKE_BUILD_TYPE=Release
    Continue? [Y/N] Y
    /home/misterdood/Games/openhexagon/bin/ does not exist!
    Create /home/misterdood/Games/openhexagon/bin/ with mkdir?
    Continue? [Y/N] Y
    Building SSVOpenHexagon requires a C++11 compiler (like clang++-3.2 or g++-4.7.2)
    All files in /home/misterdood/Games/openhexagon/bin/ will be removed
    Continue? [Y/N] Y
    Building SSVUtils...
    -- The C compiler identification is GNU 4.8.4
    -- The CXX compiler identification is GNU 4.8.4
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    SSVCMake: included
    SSVCMake: setting all defaults
    SSVCMake: setting default settings
    SSVCMake: CMAKE_BUILD_TYPE was already set to: Release
    SSVCMake: setting default flags
    CMake Error at /home/misterdood/Games/openhexagon/SSVOpenHexagon/extlibs/SSVCMake/cmake/modules/Common.cmake:87 (set):
      Syntax error in cmake code at
    
        /home/misterdood/Games/openhexagon/SSVOpenHexagon/extlibs/SSVCMake/cmake/modules/Common.cmake:87
    
      when parsing string

        -std=c++1y -pthread \

      		-Wall -Wextra -Wpedantic -Wundef -Wshadow -Wno-missing-field-initializers
      \

      		-Wpointer-arith -Wcast-align -Wwrite-strings -Wno-unreachable-code \

      		-Wnon-virtual-dtor -Woverloaded-virtual

      syntax error, unexpected cal_SYMBOL, expecting $end (99)
    Call Stack (most recent call first):
      /home/misterdood/Games/openhexagon/SSVOpenHexagon/extlibs/SSVCMake/cmake/modules/Common.cmake:208 (SSVCMake_setDefaultFlags)
      CMakeLists.txt:7 (SSVCMake_setDefaults)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/home/misterdood/Games/openhexagon/SSVOpenHexagon/extlibs/SSVUtils/build/CMakeFiles/CMakeOutput.log".
    Error occured in: /home/misterdood/Games/openhexagon/SSVOpenHexagon/extlibs/SSVUtils/build
    Error was: cmake failed

The solution was to simply remove all of the new lines and backslashes from `SSVOpenHexagon/extlibs/SSVCMake/cmake/modules/Common.cmake:87-90` and put all of the CFLAGS on a single line.

Also, this is unrelated, but it'd be cool if this package could make it to Getoo's portage tree. In case it doesn't, you can install the dependencies on Gentoo by simply running the command `emerge libsfml lua sys-libs/zlib`. You may be prompted to add a keyword in order to emerge libsfml.

**Comment by SuperV1234** [comment]
CMake 3+ supports backslashes to create line continuations. I'd love to port Open Hexagon to Gentoo's package system but I have no experience with Gentoo and no time at the moment, (many university exams!) sorry.
