### ISSUE TITLE
recursiveFillIncludedLuaFileNames is broken

### ISSUE THREAD

**Issue by MultHub** [SuperV1234/SSVOpenHexagon#128]
How to reproduce:
- `u_execScript("script"..n..".lua")` (assuming that script exists)
- script *would* run, but game crashes on startup unless "script" exists

Workaround: `u_execScript (...)` (with space)

**Comment by SuperV1234** [comment]
What is the actual problem here? Is it just necessary to check whether the file exists before looking for it?

(Also, why does it work by using a space?)

**Comment by MultHub** [comment]
> Is it just necessary to check whether the file exists before looking for it?

Yes.

> (Also, why does it work by using a space?)

Because it looks for `execScript(`, without a space

**Comment by SuperV1234** [comment]
I've (quickly) rewritten the parsing function and added informative exceptions in case a Lua file doesn't exist in commit ea29a7ff8651d0ad3689dbd4e4c72cdab2d66a35
