### ISSUE TITLE
Linux: can't build using GCC 5.3

### ISSUE THREAD

**Issue by darealshinji** [SuperV1234/SSVOpenHexagon#133]
See build log: https://gist.github.com/darealshinji/fd8dc3322f7615bf0e7b
It fails at the very first target `CMakeFiles/SSVOpenHexagon.dir/src/SSVOpenHexagon/Components/CWall.cpp.o`

I'm using gcc 5.3.0 (built from source) and cmake 3.5.0 (pre-built binaries from cmake homepage) on Ubuntu 14.04.

**Comment by SuperV1234** [comment]
Looks like the SFML version is not recent enough - could you try building it with SFML from the [GitHub repository](http://github.com/LaurentGomila/SFML)?

**Comment by darealshinji** [comment]
Yes, with a current version of SFML it's working.
