### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'   what():  std::bad_alloc

### ISSUE THREAD

**Issue by amadeuspagel** [SuperV1234/SSVOpenHexagon#134]
OpenHexagon works great when I cd to the _RELEASE directory and call it with ./SSVOpenHexagon, but I get an error when I try to call it directly:

```
./SSVOpenHexagon/_RELEASE/SSVOpenHexagon 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

**Comment by MultHub** [comment]
probably because it expects the files to be in the working directory

**Comment by amadeuspagel** [comment]
If someone has the same problem just save this as oh.sh in your home directory, run `chmod +x oh.sh` and than you can start OpenHexagon with `oh.sh`

```
cd SSVOpenHexagon/
cd _RELEASE/
./SSVOpenHexagon 
```
