### ISSUE TITLE
Could you add  "J" and "L" as movement keys, for left and right?

### ISSUE THREAD

**Issue by amadeuspagel** [SuperV1234/SSVOpenHexagon#135]

**Comment by MultHub** [comment]
## How to add keys
### Step 1
Edit your config.json, find the lines with t_rotate_ccw and t_rotate_cw
### Step 2
Add the keys ._.

**Comment by amadeuspagel** [comment]
Thanks.

**Comment by MultHub** [comment]
Ancient issue, we should close this
