### ISSUE TITLE
CMake should fail if stdc++14 check fails

### ISSUE THREAD

**Issue by darealshinji** [SuperV1234/SSVOpenHexagon#138]
Right now it does this `SSVOPENHEXAGON_HAS_STDCXX14` check, but it still continues even if the C++ compiler doesn't support c++14. I think it's better if CMake would stop and tell the user that a c++14 compatible compiler is required.

**Comment by SuperV1234** [comment]
Added a new `vrm_cmake_set_cxxstd` macro to `SSVCMake`:

```cmake
macro(vrm_cmake_set_cxxstd x)
#{
    vrm_cmake_message("setting C++ standard")

    set(CMAKE_CXX_STANDARD "${x}")
    set(CMAKE_CXX_STANDARD_REQUIRED on)
#}
endmacro()
```

It is called by default by `vrm_cmake_init_project`, with `14` as the parameter.
