### ISSUE TITLE
Build on Debian testing

### ISSUE THREAD

**Issue by vanitasvitae** [SuperV1234/SSVOpenHexagon#141]
Hi!
It took me quite some time to get this built on Debian testing (stretch), but now I somewhat succeeded. I don't know all steps anymore, since I tried a lot, but here are some things I did that were not mentioned in the readme:
```
sudo apt-get install liblua5.3-dev
cd SSVOpenHexagon
cd extlibs
git clone https://github.com/SuperV1234/SSVCMake.git
cd ..
cmake .
make
cp SSVOpenHexagon _RELEASE/.
```

I don't know, if this helped, but I also symliked libsfml-{audio,graphics,window,system,network}.so to libsfml-XXX.so.2

Then I was able to run the game. Correct me, if I forgot something :)
I know, that this is probably not the recommended way of building, but after several hours of tinkering I'm okay with that :D

Also the README is outdated. It could really use a fresh workover :)
Anyway thank you for this wonderful game. I wish it was packaged in Debians repos :/

**Comment by SuperV1234** [comment]
Hello - great to hear that you managed to successfully compile and run the game!
Unfortunately both the build process and the build instructions are not very good, apologies for that.

> Also the README is outdated. It could really use a fresh workover :)

I'll look into improving it for the OSs I personally use (Arch Linux and Windows), but I would greatly appreciate a PR with Debian instructions :)

**Comment by Morxemplum** [comment]
There are now instructions to build and compile on Debian systems. This so far has been tested on Ubuntu and Linux Mint. If there are any Debian distros that are struggling to build the game, please raise a separate issue. Closing this issue.
