### ISSUE TITLE
no assets in repository?

### ISSUE THREAD

**Issue by Mistress-Anna** [SuperV1234/SSVOpenHexagon#142]
Why aren't the assets in the source repository and is there a script to fetch them elsewhere? Are they under a license which makes them unreleasable on github? Is there another reason?

**Comment by SuperV1234** [comment]
I don't like the idea of putting audio and other large assets on VCS. Having a script to fetch them is a good idea.

The easiest way to obtain the 2.0 assets right now is probably to download this version of the game:
http://vittorioromeo.info/Misc/Temp/OpenHexagonV2.0-RC2-Win32.zip

**Comment by Mistress-Anna** [comment]
The problem is that they are not versioned, the URL can become unavailable, the git repository is not self-contained, making a zip of the sources is harder to do.

**Comment by SuperV1234** [comment]
I understand your concern - I'll consider creating a separate "assets" git repository.

**Comment by SuperV1234** [comment]
@Mistress-Anna: I've created the [SSVOpenHexagonAssets](https://github.com/SuperV1234/SSVOpenHexagonAssets) repository which contains music and sounds. It is sufficient to copy its contents to a clone of the `SSVOpenHexagon` repository.
