### ISSUE TITLE
X Error of failed request

### ISSUE THREAD

**Issue by PyRectangle** [SuperV1234/SSVOpenHexagon#152]
I have compiled OpenHexagon on raspberry pi. It has worked, but suddendly there comes this error:

"X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  1 (X_CreateWindow)
  Value in failed request:  0x0
  Serial number of failed request:  50
  Current serial number in output stream:  51
AL lib: (EE) alc_cleanup: 1 device not closed".

**Comment by SuperV1234** [comment]
Does this happen on startup? Do you have a stack trace?

**Comment by PyRectangle** [comment]
Yes, it happens at startup.
There is the complete output:
[ssvuj::logReadError]                 * Line 1, Column 1
  Syntax error: value, object or array expected.

From: []
[hg::Online::connectToServer]         Connecting to server...
[::loadConfig]                        loading config
[hg::Online::connectToServer]         Failed to connect
[ssvs::AssetManager::load<T>]         imagine.ttf resource loading
[ssvs::AssetManager::load<T>]         bottomBar.png resource loading
[ssvs::AssetManager::load<T>]         creditsBar1.png resource loading
[ssvs::AssetManager::load<T>]         creditsBar2.png resource loading
[ssvs::AssetManager::load<T>]         creditsBar2b.png resource loading
[ssvs::AssetManager::load<T>]         creditsBar2c.png resource loading
[ssvs::AssetManager::load<T>]         creditsBar2d.png resource loading
[ssvs::AssetManager::load<T>]         titleBar.png resource loading
[ssvs::AssetManager::load<T>]         beep.ogg resource loading
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
[ssvs::AssetManager::load<T>]         death.ogg resource loading
[ssvs::AssetManager::load<T>]         gameOver.ogg resource loading
[ssvs::AssetManager::load<T>]         go.ogg resource loading
[ssvs::AssetManager::load<T>]         levelUp.ogg resource loading
[ssvs::AssetManager::load<T>]         openHexagon.ogg resource loading
[ssvs::AssetManager::load<T>]         swap.ogg resource loading
[::loadAssets]                        loading local profiles
[::loadAssets]                        loading hypercube music
[ssvs::AssetManager::load<T>]         cpumood resource loading
[ssvs::AssetManager::load<T>]         dischipo resource loading
[ssvs::AssetManager::load<T>]         flirtFlirt resource loading
[ssvs::AssetManager::load<T>]         gmoomh resource loading
[ssvs::AssetManager::load<T>]         johnnyDerp resource loading
[ssvs::AssetManager::load<T>]         massacrev2 resource loading
[ssvs::AssetManager::load<T>]         minimal resource loading
[ssvs::AssetManager::load<T>]         mrGawne resource loading
[ssvs::AssetManager::load<T>]         pep resource loading
[ssvs::AssetManager::load<T>]         tengil resource loading
[::loadAssets]                        loading hypercube music data
[::loadAssets]                        loading hypercube style data
[::loadAssets]                        loading hypercube level data
[::loadAssets]                        loading ultracube music
[ssvs::AssetManager::load<T>]         mazeOfMayonnaise resource loading
[::loadAssets]                        loading ultracube music data
[::loadAssets]                        loading ultracube style data
[::loadAssets]                        loading ultracube level data
[::loadAssets]                        loading cube music
[ssvs::AssetManager::load<T>]         callMeKatla resource loading
[ssvs::AssetManager::load<T>]         captainCool resource loading
[ssvs::AssetManager::load<T>]         commandoSteve resource loading
[ssvs::AssetManager::load<T>]         drFinkelfracken resource loading
[ssvs::AssetManager::load<T>]         jackRussel resource loading
[ssvs::AssetManager::load<T>]         mazeOfMayonnaise resource loading
[ssvs::AssetManager::load<T>]         milkyWays resource loading
[ssvs::AssetManager::load<T>]         starshipShowdown resource loading
[ssvs::AssetManager::load<T>]         steampunkWarlord resource loading
[::loadAssets]                        loading cube music data
[::loadAssets]                        loading cube style data
[::loadAssets]                        loading cube level data
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  1 (X_CreateWindow)
  Value in failed request:  0x0
  Serial number of failed request:  48
  Current serial number in output stream:  49
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by PyRectangle** [comment]
I fixed everything by recompiling.
I read issue https://github.com/SuperV1234/SSVOpenHexagon/issues/81, but the performance isn't that bad. You just have to activate the GL driver in raspi-config to get around 100  fps.
