### ISSUE TITLE
Build broken on windows

### ISSUE THREAD

**Issue by kiwec** [SuperV1234/SSVOpenHexagon#153]
Builds fine on Devuan (and incredibly simple build process) following https://github.com/SuperV1234/SSVOpenHexagon/issues/151.

Unfortunately, on Windows, several issues pop up :
- Boost is a dependency not mentionned in the readme
- FindLUA.cmake has some issues finding liblua52.lib, since it's released as liblua52.a
- SSVUtilsJson isn't provided in extlibs (works fine in linux though ?)
- SSVCMake is required for SSVMenuSystem, but not provided

I stopped there since I was using build-win.bat, and build-win-new.sh probably needs a specific build system (MSYS2?).

**Comment by Morxemplum** [comment]
Build instructions have been completely rewritten on July 16th. Closing this.
