### ISSUE TITLE
Resolve Conflicting IDs in JSON files

### ISSUE THREAD

**Issue by Morxemplum** [SuperV1234/SSVOpenHexagon#182]
This one should be straightforward if you've played the game for long enough.

This issue is dedicated to what happens when two levels from two different level packs use IDs with the same names. This causes conflicts between one or both of the packs and creates a series of bugs. We just need to stop this overlapping from happening and make sure that it's selecting the correct assets that come from their level pack.

I think a common way to do this is to maybe add a pack prefix to the IDs based off folder name? (There can't be two folders with the same name in the Packs folder)

**Comment by Promethium45** [comment]
I believe levels should all have different IDs between packs anyway, and I think a naming structure could be used. Maybe something like:
_**com.Author.LevelPack.LevelName**_

**Comment by Morxemplum** [comment]
Yes. I do agree that we should have naming conventions when it comes to assigning IDs to our assets, but the problem is that not everyone is going to follow these conventions (or know about it in the first place), so we'll probably have to hard-code this convention ourselves. This way we don't have to worry about following a specific convention when utilizing our IDs

**Comment by SuperV1234** [comment]
@Morxemplum: I think we should require `"name"` and `"author"` fields in the pack JSON, and automatically generate the ID from those two. The author field could be automatically generated via SteamID, as well.

**Comment by AlphaPromethium** [comment]
@SuperV1234 with that approach, what happens for authors who don't install the game on Steam? Or will this game only be accessible on Steam soon?

**Comment by Morxemplum** [comment]
@SuperV1234 This sounds splendid. If you could automatically add the pack and the author to an inputted id in the JSON that can definitely minimize conflicting IDs.

@AlphaPromethium most likely they'll have to fill in the "author" part manually for the concatenation to work. Having it on Steam will just simplify the process.

**Comment by Morxemplum** [comment]
Moved this to In progress seeing how pack info JSONs are now updates to require you to put an author, a version number, and a "disambiguator", which I guess is made to try and stop conflicting IDs from happening. Not the best solution, but I think it works.

**Comment by AlphaPromethium** [comment]
So what error handling will be put into place if a conflicting ID occurs? And what happens to the original level with the "correct" ID?

**Comment by Morxemplum** [comment]
@AlphaPromethium This should be minimized with the "disambiguator" property. I think this was Vee's solution to this issue. I might as well close this issue because it's "solved" per se.
