### ISSUE TITLE
[Must Have] - Setup Unit Tests

### ISSUE THREAD

**Issue by AlphaPromethium** [SuperV1234/SSVOpenHexagon#202]
Should be simple to understand—when someone implements a feature, fixes a bug, etc., every issue should be tested with a unit test so that it's proven to work and it doesn't accidentally break something else. No one should expect everything to work 100% of the time.

Running unit tests should be done in its own directory, _"tests"_. For the game's UI, unit tests should not be testing elements on the UI, but rather the code called by an element.

File structure may be dependent on the unit testing framework used, but ideally something like this should be used:
```
tests
|_ SSVOpenHexagon
   |_ Components
   |  |_ CCustomWallTests.cpp
   |  |_ CPlayerTests.cpp
   |  |_ CWallTests.cpp
   |
   |_ Core
   |  |_ CCustomWallManagerTests.cpp
   |  |_ DiscordTests.cpp
   |  |_ HGGraphicsTests.cpp
   |  |_ HGScriptingTests.cpp
   |  ...
   ...
```

A/C:
1. A unit test framework is used and "tests" directory is setup.
2. [Optional] For every recent issue worked on, at least 1 unit test should be written to test that it works as expected. Could put this as a card of its own.
3. [Optional] The game's core gameplay code should be tested. Could put this as a card of its own.

_Once this issue is complete, every new issue being worked on should have at least 1 unit test, and PR reviewers will be able to inspect the test. Optionally, we could have a new column in the "Projects" tab named "Testing" for collaborators to test the new feature/bugfix/etc. and also inspect the created unit test(s) for that issue._

**_Priority: Must Have_.**

**Comment by AlphaPromethium** [comment]
Feel free to leave any unit testing framework suggestions here! I had a quick look and Google Test (GTest) may be suitable.

**Comment by Morxemplum** [comment]
I agree that regression testing is an absolute must for any decent program, and I don't think Open Hexagon is any exception. A test suite for Open Hexagon as a whole would be very nice to have to not only help patch bags, but heavily lower the odds of any new bugs appearing.

**Comment by SuperV1234** [comment]
I've always wanted to try [`doctest`](https://github.com/onqtam/doctest). It seems modern and super lightweight. This is a good opportunity.

**Comment by AlphaPromethium** [comment]
Dragging this back into todo for the time being as I am not able to get enough time to work on it. If anyone else would like to pick this up and implementing doctest that is fine by me! Just be sure to pull my branch to get my current progress! :>

**Comment by SuperV1234** [comment]
Unit tests are now available. Just stick `.cpp` files in the `test/` folder and they will be picked up and executed when running `make check`. Keeping issue open so that we can run unit tests as part of CI @InfoTeddy

**Comment by InfoTeddy** [comment]
I'll look at the tests in a bit. If they work fine then I'll make a PR.
