### ISSUE TITLE
Add an option to disable leaderboards for a level

### ISSUE THREAD

**Issue by Morxemplum** [SuperV1234/SSVOpenHexagon#204]
There are some levels that are designed to competitive, but there are other levels that aren't meant to have a competitive aspect at all, so I think that it would be fair to disable leader boards for levels that aren't meant to have a competitive aspect (such as tutorial levels like Baby Steps or a new upcoming breed of levels what I dub "automation" levels, where the level plays itself).

**Comment by Morxemplum** [comment]
I'm currently post poning this issue as leaderboards are currently not available at the moment, so this would not be testable.

**Comment by AlphaPromethium** [comment]
I think only level packs that are published on Steam should have leaderboards and everything else should not, _excluding 'cube' and 'hypercube' obviously_.

**Comment by Morxemplum** [comment]
Fair enough. This would be difficult to do and also Steam packs can update their levels, which means that entire leaderboards can get wiped easily, which is the problem I believe.

Plus it's a useful function so levels like "Baby Steps" and "Evotutorial" can not have leaderboards, considering they are tutorial levels. Also levels like the "Album" level from trollbreeder's pack can not have a score on it because it's not meant to be scored.

**Comment by AlphaPromethium** [comment]
Fair point with those tutorial levels. I suppose in that case it does make sense, but what if I was to go into the code and set the toggle to `true`? Would that mean I will have my own leaderboard for it now? There may need to be some sort of validator, which could just be the hashed checking.

I think that would depend on how the leaderboard is implemented. If a level was to be updated in some way I do believe the leaderboard for that level should be wiped.

**Comment by Morxemplum** [comment]
By modifying the code to make it true, you'll already make a new validator for it, so it won't be the same validator that it was before. And again, what's the point of enabling leaderboards for a tutorial level? Literally everybody is going to have the same score regardless, making a leaderboard pointless. There's no real motive for enabling a leaderboard for a tutorial level.

And figuring out how to preserve records from a previous version would be an interesting issue to raise and solve.

**Comment by AlphaPromethium** [comment]
Nono, I now agree we should disable leaderboards with an option/toggle for, for example, tutorial levels. You made a good point. I just meant if I _could_ do that, then what _would_ happen?

I'm saying this because I remember back in 2013 leaderboards, if I and 19 other people did the exact same change in some code, there would be a completely new leaderboard with us and only us 20 people in. This is something I want to prevent as it's unofficial from the actual level. If this has already been solved then good job! I have obviously been out of the loop about that.

**Comment by Morxemplum** [comment]
Well considering that if the leaderboards can only be done with packs that are available on Steam, we can check the contents of what the pack has on steam and get their validators (which we can dub the "certified" validator) and compare it to our validator. If it doesn't match the certified validator then don't even send the score online because it doesn't match the certified validator. It's a nice solution.

**Comment by AlphaPromethium** [comment]
Not a bad idea. It's something we can start with.

**Comment by Morxemplum** [comment]
Leaderboards for a level can be disabled server side. Closing
