### ISSUE TITLE
Remove Dynamic FPS from the game

### ISSUE THREAD

**Issue by Morxemplum** [SuperV1234/SSVOpenHexagon#212]
This is probably the reason that issue #199 exists. I'm sure Vee has pointed this out by now but Dynamic FPS is very old and this is legacy 1.92 logic that I don't think will survive. It pretty much the cause of bug #199 and if we can get rid of Dynamic FPS entirely, we may be able to mark 199 as resolved.

Any claims that it makes the game smoother can easily be discredited by simply just setting a higher FPS limit. Not the highest priority but it's worth noting.

**Comment by SuperV1234** [comment]
Another reason to do this is for the replay and leaderboard system. Static FPS guarantees determinism of game logic across different FPS values, while dynamic FPS doesn't.

**Comment by Morxemplum** [comment]
Since 2.0.3, you can no longer switch to dynamic FPS. 2.0.3 now forces all players to play the game on a constant tick rate for logic. Closing this issue because it's done.
