### ISSUE TITLE
Fix bugged "cube master" achievement

### ISSUE THREAD

**Issue by Morxemplum** [SuperV1234/SSVOpenHexagon#215]
For some reason, "Cube Master" isn't tracking progress of the achievement and it doesn't get granted when a user completes all of the levels. This issue is raised to hopefully fix the bug and grant the achievement.

**Comment by Morxemplum** [comment]
It's useful to convert some of the notes into Issues because you can do more with issues than you can with notes.

**Comment by SuperV1234** [comment]
Fixed in eb944687751cd6fd853bab57c4d48cb0b293e694.
