### ISSUE TITLE
[Should Have] - Setup to run on Debian systems

### ISSUE THREAD

**Issue by AlphaPromethium** [SuperV1234/SSVOpenHexagon#220]
As the title says.

A/C:
1. The project is able to compile on any debian system.
2. The README is updated.

**_Priority: Should Have._**

**Comment by Morxemplum** [comment]
This also covers issues #141 and #124. :)

**Comment by AlphaPromethium** [comment]
I will be creating a PR for this card alongside the other issue I am working on, #203.
