### ISSUE TITLE
Rotation doesn't invert at increments when at cap

### ISSUE THREAD

**Issue by Morxemplum** [SuperV1234/SSVOpenHexagon#223]
Self explanatory. Can easily be fixed.

**Comment by AlphaPromethium** [comment]
Could ya be more descriptive on this card? I don't entirely understand what this means.

**Comment by Morxemplum** [comment]
@AlphaPromethium When a level increments, it inverts the direction of the rotation speed after increasing it by the increment value. However, when the rotation speed cap is reached, it doesn't perform this behavior at all and it will stay rotating in one specific direction.

**Comment by AlphaPromethium** [comment]
Ah, ok I see.

**Comment by Morxemplum** [comment]
I already know what's wrong with the code, but I'm working on issue #225 right now and I'll get to it as soon as I'm done with that.
