### ISSUE TITLE
Improve collision logic on Curving Walls

### ISSUE THREAD

**Issue by Morxemplum** [SuperV1234/SSVOpenHexagon#235]
I think one of the biggest complaints I've seen Open Hexagon players make about curving walls at the moment is the fact that you will die if you try and touch the side of them if they spin into the player. I think the best thing we need to do to help make the Hypercube pack a bit more tolerable to the community is if we improved the collision logic so that way touching the sides of curving walls would push the player instead of killing them.

I know this is a current WIP but I think it's important to raise this as an issue just so it's tracked.

**Comment by AlphaPromethium** [comment]
As someone who was once an elite player, I'd say touching the side of moving walls adds to the challenge. I see it as being hit by a wall as normal, but from its side. I feel this is more appropriate as a level property/toggle, something like `l_setCanTouchCurveWallSide(bool)`.

That's just me, tho.

**Comment by Zly-u** [comment]
Actually, I will consider on implementing that. Thank.

**Comment by Zly-u** [comment]
Or maybe we could make this type of walls as a different type that does a kill on touch in any way.

**Comment by Morxemplum** [comment]
I don't like the idea of making it a togglable function, because that can add a lot of confusion to players. They won't explicitly know if they can touch the side of curving walls or not, so they're going to make the assumption that they can not. I think it should be a default mechanic, not something that can be toggled. Just saying.

**Comment by Zly-u** [comment]
Nah you are just a casual.

**Comment by AlphaPromethium** [comment]
Then I don't believe players should touch the side of curving walls at all. It doesn't make sense to imo.

**Comment by Morxemplum** [comment]
I remember this being a common complaint amongst competitive players, and I think it's one of the bigger reasons why they hate curving walls in general. Improving the collision by default can at least make curving walls a bit more tolerable to players.

**Comment by AlphaPromethium** [comment]
Then I say to them, `git good`.

... `git: 'good' is not a git command. See 'git --help'.`

**Comment by Zly-u** [comment]
y'all make no sense, I be fixing this thing anyway doe.
