### ISSUE TITLE
[Must Have] - Remove (or heavily restrict) the "io" and "os" libraries in Lua

### ISSUE THREAD

**Issue by Morxemplum** [SuperV1234/SSVOpenHexagon#237]
For anybody who has a deep knowledge of Lua, you know that this is an issue that must be taken seriously. 

The "io" and "os" libraries are very powerful libraries in Lua. Some of the functions are harmless, but there are others that are capable of doing serious damage. One of the best examples being "os.execute", which can allow Lua scripts to run commands to the terminal of a given operating system. This can be used to perform malicious actions, such as shutting down a computer or deleting entire hard drives (both of these examples have actually been done before in Open Hexagon history).

The "io" library is capable of doing the same damage, such as overwriting critical files, jamming other packs to be dysfunctional, or write malicious files in the first place. We can either remove this library completely or restrict what file types it can write and where it can write them. 

I think it's important that for the upcoming release, it's important that this issue must be handled, or people can start using Open Hexagon as a weapon against people they don't like. It has been done before, and I don't want to see future cases of this happening.

**Comment by AlphaPromethium** [comment]
Mate that priority tag idea was mine grrrrrrrrrr I am claiming copyright grrrrrrrrrrrr.

**Comment by Morxemplum** [comment]
Hire yourself a lawyer let's see how far this can go :joy:

**Comment by AlphaPromethium** [comment]
I already won.

**Comment by Morxemplum** [comment]
Sure mate sure.

**Comment by Zly-u** [comment]
shut the fuk ya babies
