### ISSUE TITLE
Allow color pulses to properly support negative values in Styles

### ISSUE THREAD

**Issue by Morxemplum** [SuperV1234/SSVOpenHexagon#241]
This was hiding in the back of my head and it didn't come to light until recently. I've noticed with the pulse field that it doesn't properly support negative values. Why is this a problem? This limits the possibilities of styles that can be made. 

A good example to demonstrate: Start off with a color of (0, 255, 0, 255), which is a fully bright green. Now pulse that by (255, -255, 255, 0) to get (255, 0, 255, 255), which is magenta. 

However, if you try to do this using Open Hexagon styles, you will actually pulse to white instead of magenta, which easily tells me that negative values do not have proper support. There is a demonstration of negative pulses in the Pointless style, but I don't feel like these are negative pulses being used properly (and as far as I know, I don't see a noticable difference if you remove the negative value).

This may either be easy to implement or very difficult. But all I know is that it is important to support negative values in pulsing to increase the number of possibilities that can be created using pulses.

**Comment by AlphaPromethium** [comment]
I agree, or we could make it be `from` colour `to` another colour.

For example,
```json
"value": [0, 255, 0, 225], "pulse": [255, 0, 255, 255] // lime green => magenta
"value": [0, 255, 0, 225], "pulse": [255, 255, 0, 128] // lime green => cyan (half transparent)
"value": [255, 0, 0, 225], "pulse": [0, 0, 0, 0]       // red => transparent
```

And to not pulsate colours, either remove `pulse` from the style JSON or set it to the same as `value`.

**Comment by Morxemplum** [comment]
That's not necessarily a "pulse" then. That's a "start" and "end" color.

I would love to do more sophisticated pulses where we can have multiple points for color, but that's not what I'm trying to accomplish with this issue at the moment. That'd be an entirely new issue on its own and a completely new feature
