### ISSUE TITLE
Github Wiki

### ISSUE THREAD

**Issue by treier57lol** [SuperV1234/SSVOpenHexagon#253]
So, I wanted to help make a wiki page for the repo, and as it turns out, I already have permissions to edit and add pages on the wiki. I read on the GitHub Docs that by default, only contributors can edit the wiki. That still doesn't seem very safe, as you can't trust every contributor and the wiki doesn't have pull requests so a maintainer can't even check and accept changes, they happen instantly.

To prove this, you should see that I made some mockup wiki pages. Although I'm happy with this base for a wiki, these were changes without review and proper permission, so it would be understandable if these were removed. GitHub should add support for wiki pull requests, as it isn't good that I made a small change to the repo and now have full access to the wiki.

**Comment by Morxemplum** [comment]
I didn't even know this was a thing until now, but this is definitely a concern. @SuperV1234 You may wanna address this.

**Comment by treier57lol** [comment]
I will also add that there doesn't seem to be a way to block any contributor from making changes to the wiki without disabling the wiki altogether or blocking the individual (don't worry, I won't make any more changes unless you want me to). If I were to be blocked, it would still allow any other contributor to make changes.

**Comment by InfoTeddy** [comment]
> I will also add that there doesn't seem to be a way to block any contributor from making changes to the wiki without disabling the wiki altogether or blocking the individual

Huh? It looks like there's a checkmark box in settings that says "Restrict editing to users in teams with push access only", and its subheading says "Public wikis will still be readable by everyone.", and it's also right under the "Wikis" checkmark box. Looks like this was originally named "Restrict editing to collaborators only" and [the GitHub docs haven't updated to the new name](https://docs.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis).

**Comment by Morxemplum** [comment]
If it restricts editing to **collaborators** then that's another story. However, I don't think it should be something that can be modified by **contributors**, because this can very easily lead to vandalization (which has happened many times on a Wikia page of Open Hexagon).

**Comment by treier57lol** [comment]
Yea, it does say **collaborators**, but I'm just a **contributor** and still have access. Could this be a typo? A bug in GitHub?

**Comment by InfoTeddy** [comment]
Well, like you said, by default it allows contributors. You have to explicitly opt-in to allowing only collaborators to edit the wiki. There's no bug anywhere except the fact that the default is to allow contributors.

**Comment by treier57lol** [comment]
But there is no option for contributors? The option for collaborators is enabled by default. If it was disabled, it would, quote: "allow anyone with a GitHub account to edit your wiki."

**Comment by InfoTeddy** [comment]
Okay, you seem to be misunderstanding.

There are two modes of access the wiki is in: mode 1 allows editing by both contributors and collaborators, and mode 2 only allows collaborators to edit. This mode is toggleable by the single checkbox I mentioned above. If the checkbox is unticked, the wiki is in mode 1, and if the checkbox *is* ticked, the wiki is in mode 2.

**Comment by treier57lol** [comment]
By the checkbox you mean "Restrict editing to users in teams with push access only"? If you're saying that checkbox toggles between the supposed 2 modes, then how come I still have the "Restrict editing to collaborators only" checkbox?
![Screenshot_20200729_210500](https://user-images.githubusercontent.com/33978534/88836538-81929180-d1df-11ea-98aa-e96e934d0b4b.png)
The wiki isn't out of date. Is "Restrict editing to users in teams with push access only" an option for only collaborators or organizations?

**Comment by InfoTeddy** [comment]
Ah, yes, my bad. I was looking at a repository owned by an organization, and only those repos have it say "users in teams with push access". If it's a repo owned by an individual account, it says "collaborators".

My mistake.

**Comment by SuperV1234** [comment]
As long as it's restricted to contributors, I think it's OK. If anyone acts maliciously we can revert changes and block them.

**Comment by treier57lol** [comment]
Good to hear. What about the changes I made? Will you keep them?

**Comment by SuperV1234** [comment]
Your changes seem good. I don't have a plan for the Wiki, and to be fair not enough free time to manage it. Would you be interested in taking care of the Wiki?

**Comment by treier57lol** [comment]
Yea, I'd be happy to help with that!

**Comment by Morxemplum** [comment]
I guess this issue is resolved then
