### ISSUE TITLE
Move the "Workshop Tutorial" to the GitHub Wiki

### ISSUE THREAD

**Issue by treier57lol** [SuperV1234/SSVOpenHexagon#257]
[Workshop Tutorial](https://openhexagon.org/workshop)

This would help with moving documentation into one place, the wiki. If my assumption is correct, then the tutorial seems to be written in Markdown already, so moving it over shouldn't be very hard.

**Comment by Morxemplum** [comment]
Great idea. In addition, I think there should also be some pages in regards to the JSONs and all their possible attributes, considering I know that's another area that people will need help on. And if you are in the mood for it, maybe an introduction to pack developing in general.

**Comment by treier57lol** [comment]
OK, so I tried to convert the Workshop Tutorial from HTML to Markdown with an online converter and it's 99% accurate, some tweaks here and there, but a little problem. GitHub Flavored Markdown doesn't support footnotes, or at least they don't work. [This](https://github.com/jbt/markdown-editor) Markdown editor is supposedly using GFM and footnotes work fine there, but when I try to make footnotes in GitHub, they don't work. I sent feedback about this to GitHub. I'm not sure if this is a bug or footnotes are just not implemented.

**Comment by Morxemplum** [comment]
Uhhhhh you do realize there is a native markdown document you could use, right?

**Comment by treier57lol** [comment]
...wait, it was on the repo all this time? DAMN IT. Anyway that's not the point, footnotes still don't work, but thanks for pointing that out.

**Comment by treier57lol** [comment]
Alright, I found an issue about adding footnotes [here](https://github.com/github/markup/issues/498), which was closed but never reopened, where some had pointed to a SO thread with alternative methods for using footnotes. I ended up using `<a href="#note1" id="note1ref"><sup>1</sup></a>` and `<a id="note1" href="#note1ref">↩︎</a>` to make footnotes work like they do on the website. It's not real Markdown footnotes but they behave exactly the same, so it's good enough for now. I commited the page to the wiki over [here](https://github.com/SuperV1234/SSVOpenHexagon/wiki/Workshop-Tutorial).
