### ISSUE TITLE
Dynamic colors stay pink/magenta after hue 360

### ISSUE THREAD

**Issue by Morxemplum** [SuperV1234/SSVOpenHexagon#259]
Dynamic colors work off the hue properties. However, how hue works is that it works from 0 to 360. You cannot get a hue that is higher than 360. When a dynamic color goes past the 360 hue, it stays at pink and it won't loop over.

What I plan on doing is when a dynamic color goes over 360, it will loop over through modulo into the next cycle. This shouldn't be hard to do.

**Comment by Zly-u** [comment]
Isn't on hue 0 and 360 the color is red, not magenta? First time hearing it's magenta on those values.

**Comment by Morxemplum** [comment]
From what I've seen it get stuck on pink/magenta, which is weird. But the PR I linked above solves this issue.

**Comment by Zly-u** [comment]
Alright
