### ISSUE TITLE
[Should Have] Upgrade the Lua binding library

### ISSUE THREAD

**Issue by Morxemplum** [SuperV1234/SSVOpenHexagon#292]
I initially made this argument on Discord but I would also like to raise it as an issue on here because I think it could be useful.

Currently we are using the [luawrapper library](https://github.com/tomaka/luawrapper) (2010 version), which is a 10 year old script that we are using to run Lua code on Open Hexagon. What's the problem with this code? Well...

- The person who wrote the module, tomaka, is no longer maintaining the module, meaning we won't be able to get anymore updates from them
- The module has difficulty working with modern C++ features that are introduced in C++11 and above, which means it can be difficult to work with. This can also hinder our abilities to try and implement new features for Open Hexagon.
- In modern day standards, the wrapper now runs pretty sluggish and could be one of the causes of lag on the Open Hexagon game. 

We cannot keep this module forever. There is bound to be a point where this module is going to harm us more than it will benefit us. Fortunately, there is a new Lua binding library that I've come across that can solve all of these issues. I've come across the [sol2 library](https://github.com/ThePhD/sol2). This library not only fixes all of the issues we have with the current binding library, but it can also...

- Be very easy to integrate, considering that it is "header only"
- Upgrade us to Lua 5.3, a more recent version of Lua that has some nifty new features that I think would be essential for some future features.
- Can be updated at any time, if we want to support a new version of Lua or we want to get even more performance improvements. 

The only issue that I can really see coming from this is the incompatibilities that will be introduced to pack developers when we move to Lua 5.3, as the only worrying incompatibility with 5.3 is integer support. But it's an issue that can easily be fixed and any other incompatibilities are very niche or too low level for any pack developers to worry about. If we can implement this correctly, there should be no issue with pack developers. This is something that should really be considered when we make Open Hexagon 2.0.3 or 2.0.4.

**Comment by Morxemplum** [comment]
I mean we've incorporated LuaJIT with #329, which is a huge performance increase in Open Hexagon. However, this will downgrade us to 5.1, because surprise surprise, we were on 5.3 before this. 

I don't know if that means that this issue is resolved. @SuperV1234 Would you consider this solved then? Was thinking about closing this issue.

**Comment by SuperV1234** [comment]
I think we can close this issue for now.
