### ISSUE TITLE
Death/Fail animation speed seems to be tied to the FPS

### ISSUE THREAD

**Issue by 0x4kgi** [SuperV1234/SSVOpenHexagon#312]
I'm talking about the hexagon expanding outwards to your character when hit a wall, not sure what to call it.

Here's some GIFs of what I'm talking about:

<details>
<summary>On VSync (75hz)</summary>

![a1XpDQ1Jwr](https://user-images.githubusercontent.com/17591127/103167999-cdb73000-486a-11eb-9708-30dce57897d6.gif)

</details>

<details>
<summary>On 200 FPS (capped)</summary>

![gkRE2DZ8zv](https://user-images.githubusercontent.com/17591127/103168029-fccda180-486a-11eb-8034-6e5af34fe634.gif)

</details>

<details>
<summary>On Unlimited</summary>

![qaeSAYfb6r](https://user-images.githubusercontent.com/17591127/103168071-2981b900-486b-11eb-9882-0bad51854bf8.gif)

</details>

It doesn't affect gameplay at all, but I feel like this is a bug, a really minor one.

**Comment by IvoryDuke** [comment]
I confirm the issue and have found out the cause.
I should be able to address it in a relatively small amount of time.

**Comment by IvoryDuke** [comment]
@0x4kgi thanks for the report.
https://github.com/SuperV1234/SSVOpenHexagon/pull/313
