### ISSUE TITLE
openhexagon.org is down

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [SuperV1234/SSVOpenHexagon#415]
https://openhexagon.org redirects to http://ww1.openhexagon.org/ which is a blank page.

There appears to be some HTML that loads adsense and a few other js+css items, but no actual content in the body.

**Comment by Pakins0** [comment]
openhexagon.org is no longer an official site for the game. someone stole the link a while back iirc.

**Comment by ColonelThirtyTwo** [comment]
That's a bummer. I've updated the Arch Linux wiki, though there's probably other sites that use the old domain.

**Comment by vittorioromeo** [comment]
The official website is now: <https://vittorioromeo.com/openhexagon.html>
