### ISSUE TITLE
Version 1.92 for linux detected as malware

### ISSUE THREAD

**Issue by christophprokop** [SuperV1234/SSVOpenHexagon#416]
It was the binary openhexagon.x86_64 taken from OpenHexagonV1.92.tar.gz for Linux.

Thought you might want to know about this.

https://www.virustotal.com/gui/file/817c529c51c1f63ffd98ce8d31a52f09c31a3469bf8ec55cfa35ce47dcca9c94/detection

**Comment by Bauumm** [comment]
Well 1.92 doesn't restrict the lua scripting at all, so it allows packs to execute system commands, create and delete directories etc.
So depending on what pack you install it may become malware.

I highly recommend you play the newer version of the game on steam instead.

**Comment by christophprokop** [comment]
oh, that explains it - thanks for your answer!
