### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by SuperV1234** [SuperV1234/SSVOpenHexagon#92]
I have looked around the internet for a good solution to email validation (send an email with a special link to activate registered account). Unfortunately I haven't been able to find a C++ oriented solution and I've never dealt with mail servers before - I'm in need of some guidance here... or maybe I'll just scrap the feature for the 2.0 release, since it's taking way too long

**Comment by Morxemplum** [comment]
I'm guessing this has something to do with the leaderboards, back when they were functional. Fortunately, we don't need to use an email for validation anymore. The Steam Release uses Steam IDs as an easy way to validate accounts and stop duplication. I'm confident enough to say this issue can be closed.
