### ISSUE TITLE
build-repository-oh.sh reports success even though the build was actually unsuccessful

### ISSUE THREAD

**Issue by CrazyCrab** [SuperV1234/SSVOpenHexagon#94]
It should report what's wrong instead.
Here is the output produced by the script.
https://gist.github.com/CrazyCrab/7c1b316b1c19136d729d/raw/5265e3d0e6fae18abd4ded43434119427abfd2a4/build-repository-oh-output.txt

**Comment by Morxemplum** [comment]
build-repository-oh is deprecated, making this issue no longer relevant. Closing.
