### ISSUE TITLE
Download page for Packs

### ISSUE THREAD

**Issue by mhanne** [SuperV1234/SSVOpenHexagon#96]
Hi, first wanted to thank you for this brilliant game! :)

I've recently reinstalled it on my laptop and when I went to grab the extra level packs from your site, the link only got me to a filebrowser-like thing that says "empty":
http://vittorioromeo.info/Downloads/OpenHexagon/LevelPacks/

I've found most of the Packs I was looking for in this file: http://www.mediafire.com/download/ndznngiri9cwchf/Open+Hexagon+%28mit+Packs%29.zip

But I'd prefer getting them from a trustworthy source such as your site.

**Comment by Morxemplum** [comment]
With the Open Hexagon Level Pack Repository application existing to serve this purpose (https://filedn.com/le5y28USRPa0EAg8QLxKklH/Open%20Hexagon%20Levelpack%20Repository/Open%20Hexagon%20Levelpack%20Repository.exe) and the upcoming Steam release to hopefully have Workshop support, this issue has been solved. Closing.
